# Site settings
title: hopon.AI
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.hopon.ai" # the base hostname & protocol for your site
author: Copyright Â© 2020 hoponAI. All Rights Reserved
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
